# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-27 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20180727_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='daet_added',
            new_name='date_added',
        ),
    ]
